export const SET_SONGS = 'SET_SONGS';
export const ADD_SONG = 'ADD_SONG';
export const SET_SONG_ACTIVITY = 'SET_SONG_ACTIVITY';
export const RESET_SONGS_ACTIVITY = 'RESET_SONGS_ACTIVITY';
export const UPDATE_SONG = 'UPDATE_SONG';
export const DELETE_SONG = 'DELETE_SONG';
export const UPDATE_MULTIPLE_SONGS = 'UPDATE_MULTIPLE_SONGS';